/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ifstorage;

import javax.swing.JFrame;

/**
 *
 * @author khadu
 */
public class InProdEstoq extends javax.swing.JFrame {

    /**
     * Creates new form InProdEstoq
     */
    public InProdEstoq() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdicionar = new javax.swing.JToggleButton();
        btnCancelar = new javax.swing.JToggleButton();
        tfCampoCNPJ1 = new javax.swing.JTextField();
        tfCampoNome1 = new javax.swing.JTextField();
        tfCampoCNPJ = new javax.swing.JTextField();
        tfCampoNome = new javax.swing.JTextField();
        lblAdicionaProdutoTitle = new javax.swing.JLabel();
        lblCodigoDesc = new javax.swing.JLabel();
        lblNomeDesc = new javax.swing.JLabel();
        lblUnidadeDesc = new javax.swing.JLabel();
        lblQuantidadeDesc = new javax.swing.JLabel();
        lblQuantidadeDesc1 = new javax.swing.JLabel();
        tfCampoCNPJ2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        btnAdicionar.setBackground(new java.awt.Color(25, 81, 40));
        btnAdicionar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        btnAdicionar.setText("ADICIONAR");
        btnAdicionar.setBorder(null);

        btnCancelar.setBackground(new java.awt.Color(144, 2, 8));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(null);
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancelarMousePressed(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tfCampoCNPJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCampoCNPJ1ActionPerformed(evt);
            }
        });

        tfCampoCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCampoCNPJActionPerformed(evt);
            }
        });

        lblAdicionaProdutoTitle.setBackground(new java.awt.Color(23, 136, 44));
        lblAdicionaProdutoTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblAdicionaProdutoTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblAdicionaProdutoTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdicionaProdutoTitle.setText("Produto");
        lblAdicionaProdutoTitle.setOpaque(true);
        lblAdicionaProdutoTitle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblAdicionaProdutoTitleMouseDragged(evt);
            }
        });
        lblAdicionaProdutoTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblAdicionaProdutoTitleMousePressed(evt);
            }
        });

        lblCodigoDesc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCodigoDesc.setText("Código:");

        lblNomeDesc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNomeDesc.setText("Nome:");

        lblUnidadeDesc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUnidadeDesc.setText("Unidade:");

        lblQuantidadeDesc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQuantidadeDesc.setText("Qtd;");

        lblQuantidadeDesc1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQuantidadeDesc1.setText("N. Nota:");

        tfCampoCNPJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCampoCNPJ2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAdicionaProdutoTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigoDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfCampoNome)
                            .addComponent(tfCampoCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(lblUnidadeDesc))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(lblQuantidadeDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(lblQuantidadeDesc1)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfCampoNome1)
                            .addComponent(tfCampoCNPJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCampoCNPJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblAdicionaProdutoTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoDesc)
                    .addComponent(tfCampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeDesc)
                    .addComponent(tfCampoCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnidadeDesc)
                    .addComponent(tfCampoNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidadeDesc)
                    .addComponent(tfCampoCNPJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCampoCNPJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantidadeDesc1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMousePressed
        this.dispose();
    }//GEN-LAST:event_btnCancelarMousePressed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tfCampoCNPJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCampoCNPJ1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCampoCNPJ1ActionPerformed

    private void tfCampoCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCampoCNPJActionPerformed

    }//GEN-LAST:event_tfCampoCNPJActionPerformed
    
    int xx, xy;
    
    private void lblAdicionaProdutoTitleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdicionaProdutoTitleMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_lblAdicionaProdutoTitleMouseDragged

    private void lblAdicionaProdutoTitleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdicionaProdutoTitleMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_lblAdicionaProdutoTitleMousePressed

    private void tfCampoCNPJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCampoCNPJ2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCampoCNPJ2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InProdEstoq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InProdEstoq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InProdEstoq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InProdEstoq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                InProdEstoq produto = new InProdEstoq();
                produto.setVisible(true);
                produto.setSize(457, 400);
                produto.setLocationRelativeTo(null); // Centraliza o JFrame na tela
                produto.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE );
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAdicionar;
    private javax.swing.JToggleButton btnCancelar;
    private javax.swing.JLabel lblAdicionaProdutoTitle;
    private javax.swing.JLabel lblCodigoDesc;
    private javax.swing.JLabel lblNomeDesc;
    private javax.swing.JLabel lblQuantidadeDesc;
    private javax.swing.JLabel lblQuantidadeDesc1;
    private javax.swing.JLabel lblUnidadeDesc;
    private javax.swing.JTextField tfCampoCNPJ;
    private javax.swing.JTextField tfCampoCNPJ1;
    private javax.swing.JTextField tfCampoCNPJ2;
    private javax.swing.JTextField tfCampoNome;
    private javax.swing.JTextField tfCampoNome1;
    // End of variables declaration//GEN-END:variables
}
